version: '3'

volumes:
  db_data:
      driver: local
      name: db_data
      driver_opts:
        type: none
        device: /home/ilefhail/data/db_data
        o: bind
  wp_data:
      name: wp_data
      driver: local
      driver_opts:
        type: none
        device: /home/ilefhail/data/wp_data
        o: bind

services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wp_data:/wordpress
    depends_on :
      - mariadb
    restart: always
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes :
      - wp_data:/wordpress
    depends_on :
      - wordpress
    restart: always
  redis:
    build: ./requirements/bonus/redis
    restart: always
  adminer:
    build: ./requirements/bonus/adminer
    ports:
      - 80:80
    restart: always
  ctop:
    build: ./requirements/bonus/ctop-service
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  portfolio:
    build: ./requirements/bonus/portfolio-website
    ports:
      - 3000:80
