version: '3'

volumes:
  wb_data:
  sql_data2:

services:
  mariadb:
    build: mariadb
    volumes:
      - sql_data2:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306:3306
  wordpress:
    build: wordpress
    env_file:
      - .env
    volumes:
      - wb_data:/wordpress
    ports:
      - 9000:9000
    links :
      - mariadb
    depends_on:
      - mariadb
  nginx:
    build: nginx
    volumes:
      - wb_data:/wordpress
    ports:
      - 443:443
    links : 
      - wordpress
