version: '3'

services:
  mariadb:
    build: mariadb
    volumes:
      - type : bind
        source : /var/lib/mysql
        target : /home/ilefhail/data/db_data
    env_file:
      - .env
    ports:
      - 3306:3306
  wordpress:
    build: wordpress
    env_file:
      - .env
    volumes:
      - type: bind
        source: /wordpress
        target: /home/ilefhail/data/wp_data
    ports:
      - 9000:9000
    depends_on :
      - mariadb
    links :
      - mariadb
  nginx:
    build: nginx
    ports:
      - 443:443
    depends_on :
      - wordpress
    links : 
      - wordpress
