version: '3'

volumes:
  db_data:
      driver: local
      name: db_data
      driver_opts:
        type: none
        device: /home/ilefhail/data/db_data
        o: bind
  wp_data:
      name: wp_data
      driver: local
      driver_opts:
        type: none
        device: /home/ilefhail/data/wp_data
        o: bind

services:
  mariadb:
    build: mariadb
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
  wordpress:
    build: wordpress
    env_file:
      - .env
    volumes:
      - wp_data:/wordpress
    depends_on :
      - mariadb
    links :
      - mariadb
  nginx:
    build: nginx
    ports:
      - 443:443
    volumes :
      - wp_data:/wordpress
    depends_on :
      - wordpress
    links : 
      - wordpress
